const projects = [
  {
    id: 1,
    title: "HiLink - Travel Camp",
    info: "HiLink is a Landing Page with the principles of UI/UX, it has the best front practices and a very good looking background",
    front: "It was made with Next.js, Typescript and Tailwind",
    frontDepends: ["Next.js", "Tailwind", "Typescript"],
    color: "green",
    img: "hilink-preview.png",
    github: "https://github.com/JuanSegundo7/Travel-App",
    demo: "https://travel-landing-camp-app.vercel.app",
  },
  {
    id: 2,
    title: "Imagino",
    info: "Imagino is an AI image generator where with different type of filters, you can create images and download them in your favorite extension",
    front: "It was made with Next.js, Typescript and Tailwind",
    frontDepends: ["Next.js", "Tailwind", "Typescript"],
    color: "grey",
    img: "imagino-preview.png",
    github: "https://github.com/JuanSegundo7/Imagino",
    demo: "https://imagino.vercel.app",
  },
  {
    id: 3,
    title: "Streamvailable",
    info: "Streamvailable is a website where you can check if a movie or serie is available in your country and in which stream platform",
    front: "It was made with Next.js, Typescript and Tailwind",
    frontDepends: ["Next.js", "Tailwind", "Typescript"],
    color: "green",
    img: "streamvailable-preview.png",
    github: "https://github.com/JuanSegundo7/Streamvailable",
    demo: "https://streamvailable.vercel.app",
  },
  {
    id: 4,
    title: "Loop Mania",
    info: "Loop mania is a Gif seeker where you can find Gifs of any topic, it has a trending system where you can see the most important gifs of the moment, also it has a bookmark and share system, so you can share it with anyone you want. You can look at your saved gifs in your profile",
    front:
      "It was made with React, Redux, Typescript, Material UI, Auth0 and Axios",
    frontDepends: [
      "React",
      "Redux",
      "Typescript",
      "Material UI",
      "Auth0",
      "Axios",
    ],
    color: "grey",
    img: "loop-mania-preview.png",
    github: "https://github.com/JuanSegundo7/LoopMania",
    demo: "https://loop-mania.vercel.app/",
  },
  {
    id: 5,
    title: "Tiger Coffee - HENRY",
    info: "Tiger Coffee is the final proyect that i made in Henry. Tiger Coffee is an ecommerce that we made in group, my responsability was the esthetic of the place and a lot of the front side, like html structure, dashboard, etc.",
    front:
      "It was made with React Framework, Redux and Material-UI for the dashboard",
    back: "The back side was made with Express and Mongo DB",
    backDepends: ["Express", "Mongo DB"],
    frontDepends: ["React-router-dom", "Redux", "React", "Material-UI"],
    color: "green",
    img: "tiger_coffee_preview.png",
    github: "https://github.com/JuanSegundo7/Final_Proyect",
    demo: "https://tigercoffee.vercel.app/",
  },
  {
    id: 6,
    title: "PI DOGS - HENRY",
    info: "This is one of the final proyects that i made in Henry, in particular, this was a individual proyect in React with Redux and Postgresql, where they evaluated how were my skills in Front and Back with an Dogs Api - https://thedogapi.com/",
    front: "It was made with React Framework and Redux",
    back: "The back side is composed by Express and Postgresql",
    backDepends: ["Express", "Postgresql"],
    frontDepends: ["React-router-dom", "Redux", "React"],
    color: "grey",
    img: "dogs-preview.png",
    github: "https://github.com/JuanSegundo7/PI-Dogs-Front",
    demo: "https://pi-dogs-jsm.vercel.app//",
  },
  {
    id: 7,
    title: "Rick and Morty Api",
    info: "Rick & Morty Api is a project where i practiced Api Fetch, using differents hooks like useEffect & useState, im very happy with the result because i did it in a few days only! Motivating myself to keep practicing React and all it structure",
    front:
      "It was made with React Framework and a few hooks like useEffect & useState",
    frontDepends: ["React-router-dom"],
    color: "green",
    img: "rick-and-morty-preview.png",
    github: "https://github.com/JuanSegundo7/Rick-and-Morty",
    demo: "https://rick-and-morty-juanse.vercel.app/",
  },
  // {
  //   id: 7,
  //   title: "Colombus music",
  //   info: "Colombus music is a ecommerce project where i created the Front & Back sides in differents repositories, giving me the chance to practice the conextion between Front and Back with Apis. It was a challenge just for the fact of creating all from 0, Front (styles, components), Back (Entry Point, MVC, HTTP request, Connection with Database), Database (Sequelize) and Deploying it in Heroku",
  //   front:
  //     "It was made with React Framework where i used Axios for Api Rest and JWT for a User Global context",
  //   back: "It was made with Express.js and i used Sequelize for database, it has a MVC model and JWT security",
  //   backDepends: [
  //     "Cors",
  //     "Bcrypt",
  //     "Multer",
  //     "Express",
  //     "Body-parser",
  //     "JsonWebToken",
  //     "Express-session",
  //     "Method-override",
  //   ],
  //   frontDepends: ["Axios", "Jwt-decode", "Fontawesome", "React-router-dom"],
  //   color: "green",
  //   img: "instrumentos-react-preview.png",
  //   github: "https://github.com/JuanSegundo7/instrumentos-front",
  //   demo: "https://colombus.vercel.app/",
  // },
];

export default projects;
